flowchart LR
    A([Start])
    A --> B{"`Är det morgon
    eller kväll?`"}
    B -->|Innan lunch| C["Hälsa god morgon!"]
    B -->|Mellan lunch/kväll| D["Hälsa god eftermiddag!"]
    B -->|Kväll| E["Hälsa god kväll!"]